function(putils_src_files dst_list)
	set(options)
	set(oneValueArgs)
	set(multiValueArgs DIRECTORIES EXTENSIONS)
	cmake_parse_arguments(ARGUMENTS "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})

	foreach(arg_name ${multiValueArgs})
		if(NOT ARGUMENTS_${arg_name})
			message(FATAL_ERROR "Missing ${arg_name} argument to putils_src_files")
		endif()
	endforeach()

	foreach(dir ${ARGUMENTS_DIRECTORIES})
		foreach(ext ${ARGUMENTS_EXTENSIONS})
			list(APPEND glob_rules ${dir}/*.${ext})
		endforeach()
	endforeach()

	file(GLOB src_files ${glob_rules})
	set(${dst_list} ${src_files} PARENT_SCOPE)
endfunction()
